# Generated by Django 4.2 on 2024-02-26 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=6)),
                ('media_file', models.FileField(upload_to='blog/post/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_media', to='blog.post', verbose_name='Posts')),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
    ]
