# Generated by Django 4.2 on 2024-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
