# Generated by Django 4.2 on 2024-02-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_orderitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_payed',
            new_name='is_paid',
        ),
    ]
